(function(root){
const checked='2026-10-02';
const sources=[{name:'Gemini free-tier pricing and data use',url:'https://ai.google.dev/gemini-api/docs/pricing',checked,note:'Limited model access. Free-tier content may improve Google products. Do not paste private information.'},{name:'Groq account rate limits',url:'https://console.groq.com/docs/rate-limits',checked,note:'Limits depend on the model and account. Check your own limits; this app does not promise unlimited use.'},{name:'Ollama local/cloud FAQ',url:'https://docs.ollama.com/faq',checked,note:'Local models need suitable hardware. Local-only and cloud modes have different privacy boundaries.'}];
const tasks=[
{id:'research',name:'Research a topic',output:'A sourced brief',steps:['Find primary sources with web search. Open the original pages and record dates.','Use an available text model to compare evidence. Give it the sources, not just the topic.','Check every important claim against the source. Remove unsupported claims.'],check:['Every important fact has a source.','Conflicting sources are called out.','The brief states what is still unknown.'],prompt:'Using only the source excerpts I provide, write a short brief. Separate facts, interpretations and unknowns. Attach the source URL to each factual claim. Do not invent sources.'},
{id:'marketing',name:'Write a campaign',output:'An editable campaign draft',steps:['Write a brief: audience, offer, evidence, channel and one action.','Use a text model to create two draft angles from the same brief.','Review claims, tone and consent before sharing. No automatic posting.'],check:['No invented testimonials or sales guarantees.','Offer, price and dates match the brief.','The next action is clear.'],prompt:'Create two campaign drafts from this brief. Do not invent product benefits, statistics, testimonials, prices or deadlines. Mark missing facts as questions. Include a short checklist of claims to verify.'},
{id:'website',name:'Build a landing page',output:'A tested page prototype',steps:['Define one audience and one action. Sketch the content before selecting a builder.','Use an available coding assistant to draft accessible HTML/CSS from that brief.','Run the page locally. Check phone layout, keyboard use, forms and links before publishing.'],check:['Works on a phone without horizontal overflow.','No API keys or personal data in the code.','All buttons and links do what they say.'],prompt:'Draft a simple accessible landing page from this brief. Use no external scripts or paid services. Do not invent customer logos, claims or reviews. Explain how to run and test it locally.'},
{id:'spreadsheet',name:'Analyze a spreadsheet',output:'Checked calculations and a summary',steps:['Remove personal fields or work locally. Define the exact question and units.','Use spreadsheet formulas for totals first. A text model can help explain formulas with synthetic samples.','Reconcile totals and manually check a few rows. Do not treat fluent explanations as proof.'],check:['Totals reconcile with the source rows.','Missing values and units are explicit.','No personal records uploaded without permission.'],prompt:'Using this synthetic spreadsheet sample, propose formulas for the question below. Explain units, handling of blanks and zero denominators. Give small manual checks. Do not invent trends from missing data.'},
{id:'presentation',name:'Create a presentation',output:'An editable slide outline',steps:['Define the audience, decision and supporting evidence.','Use a text model for an outline and a slide editor for layout. Keep sources attached to claims.','Render every slide and inspect readable text, charts and citations.'],check:['Every slide has one clear point.','Numbers and claims match the sources.','Final slides are visually inspected.'],prompt:'Turn this sourced brief into a 6-slide outline. Give one clear point per slide, supporting evidence and source URL. Mark unknowns. Do not add invented data, clients or results.'}
];
function recommend(taskId,privacy,device){
const task=tasks.find(t=>t.id===taskId); if(!task)throw new Error('Choose a supported task.');
const local=privacy==='private';
const route=local?(device==='phone'?'Use redacted or synthetic input. A phone-only private-model route is not verified here. Do not upload sensitive content to a free cloud service.':'Use a local-only model through Ollama if your computer can run it. Disable cloud features, check hardware and test with synthetic data first.'):'Start with Google AI Studio for a text-model draft where its current free tier fits. Groq is an API alternative for developers, not a no-setup phone workflow. Verify eligibility and limits at the official pages.';
return {task,route,blocked:local&&device==='phone',sources,checked};
}
const api={tasks,sources,recommend};if(typeof module!=='undefined')module.exports=api;root.Compass=api;
})(typeof window==='undefined'?globalThis:window);
